version: "3.9"

services:
  postgres:
    image: ${IMAGE_NAME}:latest
    container_name: postgres
    restart: unless-stopped

    ports:
      - "127.0.0.1:${DB_PORT}:5432"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - pgdata:/var/lib/postgresql/data

    command:
      - postgres
      - -c
      - shared_preload_libraries=age
      - -c
      - search_path="\"$user\", public, ag_catalog"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - platform-net

volumes:
  pgdata:

networks:
  platform-net:
    name: platform-net
    external: true
