services:
  postgres:
    build: .
    container_name: postgres
    restart: unless-stopped

    ports:
      - "127.0.0.1:${DB_PORT}:5432"

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - platform-net

volumes:
  pgdata:

networks:
  platform-net:
    name: platform-net
    external: true
